### PR TITLE
Check for Ubuntu 16.04 and conditionally install Python 3.6 and configure ST2 to use it

### PR DESCRIPTION
**Pull request by blag**
The end-to-end tests are failing on Ubuntu 16 because they don't have Python 3.6 available, which is blocking my PR #5064:

```
not ok 36 packs.setup_virtualenv with python3 flag works
# (in test file cli/test_pack_python3.bats, line 88)
#   `RESULT=$(st2 run examples.python_runner_print_python_version -j)' failed with status 127
not ok 37 python3 imports work correctly
# (from function `assert_success' in file cli/../test_helpers/bats-assert/src/assert.bash, line 114,
#  in test file cli/test_pack_python3.bats, line 117)
#   `assert_success' failed with status 127
# 
# -- command failed --
# status : 1
# output (19 lines):
#   
#   {
#       \"action\": {
#           \"ref\": \"python3_test.test_stdlib_import\"
#       }, 
#       \"context\": {
#           \"user\": \"st2admin\"
#       }, 
#       \"end_timestamp\": \"2020-10-29T00:47:52.928925Z\", 
#       \"id\": \"5f9a1138f016f26a2a042272\", 
#       \"result\": {
#           \"exit_code\": 1, 
#           \"result\": \"None\", 
#           \"stderr\": \"Traceback (most recent call last):\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/netaddr/compat.py\\\", line 91, in <module>\
    from importlib import resources as _importlib_resources\
ImportError: cannot import name 'resources'\
\
During handling of the above exception, another exception occurred:\
\
Traceback (most recent call last):\
  File \\\"/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py\\\", line 53, in <module>\
    from st2common import log as logging\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/log.py\\\", line 32, in <module>\
    from st2common.logging.handlers import FormatNamedFileHandler\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/logging/handlers.py\\\", line 22, in <module>\
    from oslo_config import cfg\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/oslo_config/cfg.py\\\", line 336, in <module>\
    from oslo_config import types\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/oslo_config/types.py\\\", line 21, in <module>\
    import netaddr\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/netaddr/__init__.py\\\", line 18, in <module>\
    from netaddr.core import (AddrConversionError, AddrFormatError,\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/netaddr/core.py\\\", line 11, in <module>\
    from netaddr.compat import _callable, _iter_dict_keys\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/netaddr/compat.py\\\", line 93, in <module>\
    import importlib_resources as _importlib_resources\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/importlib_resources/__init__.py\\\", line 31, in <module>\
    from importlib_resources._py3 import (\
  File \\\"/opt/stackstorm/st2/lib/python2.7/site-packages/importlib_resources/_py3.py\\\", line 20, in <module>\
    Resource = Union[str, os.PathLike]\
AttributeError: module 'os' has no attribute 'PathLike'\
\", 
#           \"stdout\": \"\"
#       }, 
#       \"start_timestamp\": \"2020-10-29T00:47:52.507461Z\", 
#       \"status\": \"failed\"
#   }
# --
# 
```

This PR tweaks the `st2_pkg_e2e_test` workflow to check for Ubuntu 16 and if detected, installs Python 3.6 from the `deadsnakes` PPA and configures StackStorm to use it utilizing the `patch` utility and Bash heredocs.

### CODE REVIEW

**Comment by amanda11** [comment]
Should we have code in that is python 3 specific at this time? The formal install methods installer, ansible, puppet will still install on Ubuntu 16 and el7 with python 2.7?

**Comment by blag** [comment]
This code does not change what StackStorm itself runs under, and yes, on Ubuntu 16 and RHEL 7, StackStorm itself runs with Python 2.7.

What this change does is tweak what version of Python StackStorm uses when installing packs with the `--python3` flag (`st2 pack install --python3 mypack`). Previously it was using the system's Python 3 version, which is Python 3.5 for Ubuntu 16. Unfortunately, Python 3.5 does not implement `os.PathLike`, so we need to tell StackStorm to use Python 3.6+ when installing Python 3 packs.

One point to consider is that this should work just fine for the current unstable builds, but we might want to consider continuing to use Python 3.5 for the stable builds on Ubuntu 16 and any 3.3.x releases.

**Review by armab — CHANGES_REQUESTED** [review]
Per discussion we agreed to provide python3.6 PPA via `curl|bash` installer based on user's `y/n` input. See: https://github.com/StackStorm/st2-packages/pull/681 and we can adjust this PR afterwards.

That would be better as adding repo beforehand defeats the purpose of end-to-end tests.

File: actions/workflows/st2_pkg_e2e_test.yaml [hunk 1]
```diff
@@ -156,6 +156,32 @@ tasks:
...
+    input:
+      hosts: <% ctx().vm_info.private_ip_address %>
+      cmd: |-
+        python3 --version
+        add-apt-repository ppa:deadsnakes/ppa --yes
+        apt-get update
+        apt-get install --yes python3.6
+        patch /etc/st2/st2.conf <<EOF
+        23a24
+        > python3_binary = /usr/bin/python3.6
```
Comment (armab) [inline actions/workflows/st2_pkg_e2e_test.yaml:183]: Yeah, with python3 only support in next st2 version, from what I understand we're also removing `python3_binary` from `st2.conf`

Comment (amanda11) [reply actions/workflows/st2_pkg_e2e_test.yaml]: I have a PR in WIP that will take out the --python3 option, and therfore the python3_binary parameter etc. It's just blocked at moment with the failures on the E2E - so I can't verify I've not broken anything.

Comment (blag) [reply actions/workflows/st2_pkg_e2e_test.yaml]: I reworked this PR to obviate this.

**Comment by blag** [comment]
I reworked this to use `echo 'y' | ` when running the bootstrap script.

**Comment by amanda11** [comment]
Excellent - LGTM - should fix the E2Es.

**Comment by blag** [comment]
Once our current E2E builds finish up I'll install this branch on st2cicd and try it out. I won't merge this until it's at least tested.

File: actions/workflows/st2_pkg_e2e_test.yaml [hunk 2]
```diff
@@ -117,7 +132,10 @@ tasks:
     action: core.remote_sudo
     input:
       hosts: <% ctx().vm_info.private_ip_address %>
+      # If pipe_into_bootstrap_script is not empty, return it + " | "
+      # If pipe_into_bootstrap_script is empty, return an empty string
       cmd: >-
+        <% switch(ctx().pipe_into_bootstrap_script => concat(ctx().pipe_into_bootstrap_script, " | "), true => "") %>
```
Comment (armab) [inline actions/workflows/st2_pkg_e2e_test.yaml:138]: That should work in this particular case.

However I provided `--u16-add-insecure-py3-ppa` flag as identified more bash corner cases with the interactive mode under different environments. https://github.com/StackStorm/st2-packages/pull/682

File: actions/workflows/st2_pkg_e2e_test.yaml [hunk 3]
```diff
@@ -117,7 +132,10 @@ tasks:
...
         bash /tmp/st2_bootstrap.sh
         --<% ctx().pkg_env %>
         --<% ctx().release %>
```
Comment (armab) [inline actions/workflows/st2_pkg_e2e_test.yaml:141]: Feel free to pass that extra U16 flag to script directly without extra workflow logic as our installer is catch-all and won't fail in case of non-existent param provided.

Comment (blag) [reply actions/workflows/st2_pkg_e2e_test.yaml:141]: Even better!

Comment (armab) [reply actions/workflows/st2_pkg_e2e_test.yaml:141]: As https://github.com/StackStorm/st2-packages/pull/682 is now merged, you can add `--u16-add-insecure-py3-ppa`
